### ISSUE TITLE
VMWare direct GPU access

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#133]
In order to better test Phoenix on Linux, I need to know if it's possible to have direct GPU access by a VM running on an Windows host.

**Comment by flubbacrud** [comment]
Ok so. You cannot do direct GPU access on workstation. If you had a server (of some sort) and ran VMware ESXi on it then you would be able to do vSGA or vDGA. You card would also need to be compatible. The reason for this is your card is already presented and running the host OS, so it cannot be shared out or locked out to a single VM. ESXi is gui-less so can punch the entire graphics card to one/multiple VM's depending on what mode you choose.

since its linux I can only suggest potentially backing up and deleting the OpenGL drivers that are shipped with VMware for use on a windows host, forcing it to use the microsoft ones bundle with Windows. I doubt this would make a difference though.

**Comment by athairus** [comment]
I have no plans on running a server with its own dedicated GPU, so this isn't feasible for me. I'll just wipe one of my other computers and put Linux on them.
