### ISSUE TITLE
Backend refactor, part 2

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#233]
This issue is focused on coming up with better names for the parts of the backend in order to make their purpose more self-explanatory.

The first and most obvious change would be to rename `CoreControl` to `GameConsole`. As you can see, I'm going for a kind of skeumorphism with the name choices. A game console has controller inputs and video and audio outputs. The name `GameConsole` fits this abstraction perfectly. 

Within the game console, well, that's something I need to think about a bit more. What can we call `LibretroCore`? I'm thinking about how we could swap the game console's innards with a different motherboard, changing it into a different console, which from a programmatic perspective means using either a different API (assuming many different APIs we'll support) or different Libretro cores (the more likely scenario).

**Comment by RonnChyran** [comment]
GameConsole makes perfect sense as it describes what that such class does perfectly without being too verbose, rather than CoreControl which is rather vague and would require looking at docs or implementation to realise what it does. Likewise, LibretroCore is an obvious name that describes what that such class does — its a Libretro core, which is common knowledge. Renaming this to something like "Motherboard" or "GameChip" is just obscuring this obvious meaning for the purposes of aesthetics to fit in with the skeumorphism theme. Just like how a gamepad abstraction class would make sense to be named "Gamepad", a Video output class would be better named "VideoOutput" rather than "Television".

**Comment by athairus** [comment]
Implemented in `feature-pipeline` along with a ton of other changes as described in #249
