### ISSUE TITLE
qt5cored.dll missing

### ISSUE THREAD

**Issue by GinBunBun** [team-phoenix/Phoenix#236]
I followed the instructions to the letter and when I try to open the program it tells me qt5cored.dll is missing.

**Comment by athairus** [comment]
Hi there. I'm guessing you're running this from Windows. Are you launching Phoenix from either Qt Creator or from the mingw64 shell? Either choice ensures that the mingw64 bin directory (which contains that dll and many others) is in your PATH.

Alternatively (and I don't recommend this) you can add `C:/msys64/mingw64/bin` to your PATH.

**Comment by GinBunBun** [comment]
I was just trying to launch the compiled exe. I'm assuming theres more I have to do.

**Comment by athairus** [comment]
Try my suggestions! It should launch just fine from the mingw64 terminal or Qt Creator.

**Comment by GinBunBun** [comment]
ill try that but is there a way to run it like a regular program? if not ill have to just do what you said.

**Comment by athairus** [comment]
The problem is the dll (and that's just the first of like 2 dozen it needs) exists on your hard drive, but Windows isn't set up to look for it. The second suggestion (the one I don't recommend) would let you run it "like a regular program" but would also potentially interfere with other programs you might've installed that also use Unix-style tools. If you don't really program and you're just trying out Phoenix, you should be fine. Just remember to undo the change once we finally release and provide an installer!

**Comment by GinBunBun** [comment]
ah ok. and no i dont really program at all I just wanted to try it out because it looks really cool. I've been using launchbox and I'm not really a fan of retroarchs look.

**Comment by athairus** [comment]
I gotcha! Thanks for checking us out. Hope you like it!
