### ISSUE TITLE
Fails to build on Arch x86_64

### ISSUE THREAD

**Issue by parkerlreed** [team-phoenix/Phoenix#252]
phoenix-git from AUR

````
...
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -std=gnu++0x -Wall -W -D_REENTRANT -DQUAZIP_STATIC -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -isystem /usr/include -isystem /usr/include/SDL2 -I../externals/quazip/quazip -Iconsumer -Icore -Iinput -Irole -Iutil -isystem /usr/include/qt -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtMultimedia -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -Imoc -I/usr/lib/qt/mkspecs/linux-g++ -o obj/looper.o util/looper.cpp
/usr/lib/qt/bin/rcc -name controllerdb input/controllerdb.qrc -o rcc/qrc_controllerdb.cpp
RCC: Error in 'input/controllerdb.qrc': Cannot find file 'SDL_GameControllerDB/gamecontrollerdb.txt'
Makefile:657: recipe for target 'rcc/qrc_controllerdb.cpp' failed
make[1]: *** [rcc/qrc_controllerdb.cpp] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/packerbuild-1000/phoenix-git/phoenix-git/src/Phoenix/backend'
Makefile:69: recipe for target 'sub-backend-make_first' failed
make: *** [sub-backend-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
The build failed.
````

**Comment by Limero** [comment]
I can confirm that it currently doesn't compile correctly from the AUR. Travis-ci is not able to build the project either at the current state of the master branch, so this should not be anything Arch related.

**Comment by athairus** [comment]
Backend now contains its own submodule. The entire repo must be cloned with `--recursive` or the submodules must be set up with `git submodule update --init --recursive` in order to get this to init properly. You'll have to update your `PKGBUILD` accordingly. Sorry for not giving a heads up.

Travis failed to build the latest build in `feature-pipeline`, the branch with the new backend/frontend code we're working on. This is due to us using some ancient SDL2 library and will probably be fixed as soon as I finish typing this comment. The latest `master` build is fine: https://travis-ci.org/team-phoenix/Phoenix/builds/126983874

If things still aren't working, let me know!

**Comment by Limero** [comment]
PKGBUILD has been updated, this can be closed.

**Comment by parkerlreed** [comment]
Cheers, thanks.
