### ISSUE TITLE
Your homepage is down

### ISSUE THREAD

**Issue by ShalokShalom** [team-phoenix/Phoenix#324]
If you sold the domain, remove the link here from Github?

**Comment by brodycas3** [comment]
It's still up, https://phoenix.vg/

**Comment by ShalokShalom** [comment]
Nope, not for me. isup shows me, that its up for others.
Both, Firefox and Chrome here. 

All the other pages work.

**Comment by athairus** [comment]
The domain is not sold to anyone, we're not going anywhere. What do you get when you visit our homepage? What error?

What does `phoenix.vg` resolve to? On my box it's (and it should be for everyone) `104.236.218.193`

**Comment by ShalokShalom** [comment]
How can i check this?

This is what i get: 

http://funkyimg.com/i/2jWRz.png

**Comment by athairus** [comment]
Run `host phoenix.vg` and post the results. In addition, post what your DNS servers are.

**Comment by ShalokShalom** [comment]
phoenix.vg has address 185.53.177.31

**Comment by ShalokShalom** [comment]
two websites give me an error on test for the DNS servers

**Comment by athairus** [comment]
Please try Google's DNS (8.8.8.8 and 8.8.4.4 IIRC) and see if you get the same issue.

**Comment by ShalokShalom** [comment]
Both dont exist according to http://dnscheck.iis.se/

**Comment by brandleesee** [comment]
@ShalokShalom you have to test using the Undelegated domain test tab in the website provided.

**Comment by ShalokShalom** [comment]
And use what as Nameserver and IP?

**Comment by brandleesee** [comment]
8.8.8.8

**Comment by ShalokShalom** [comment]
![screenshot_20161124_093639](https://cloud.githubusercontent.com/assets/6344099/20591590/969c2eda-b229-11e6-88f5-664d2d3db30f.png)

**Comment by brandleesee** [comment]
@ShalokShalom Domain name should be phoenix.vg
@athairus I can see the website just fine, however, there are some errors which make me think that not all dns/providers are effective. fyi I am using Google's.

I provided screenshots because I do not know if the links to the tests have an expiry.

### my results for undesignated
![screenshot from 2016-11-24 09-49-12](https://cloud.githubusercontent.com/assets/12674437/20591975/96b0ab1a-b22b-11e6-9406-7ce0120e4e82.png)
![screenshot from 2016-11-24 09-49-44](https://cloud.githubusercontent.com/assets/12674437/20591976/96b60e70-b22b-11e6-9d61-e1e8aa0d72e6.png)
![screenshot from 2016-11-24 09-50-10](https://cloud.githubusercontent.com/assets/12674437/20591977/96ba816c-b22b-11e6-9cc2-c2edce262388.png)

### my results for designated
![screenshot from 2016-11-24 09-53-00](https://cloud.githubusercontent.com/assets/12674437/20592130/55029736-b22c-11e6-8e53-382eee10e5c7.png)
![screenshot from 2016-11-24 09-53-56](https://cloud.githubusercontent.com/assets/12674437/20592131/550e3550-b22c-11e6-92cb-db47b44c8250.png)
![screenshot from 2016-11-24 09-54-13](https://cloud.githubusercontent.com/assets/12674437/20592132/55102b58-b22c-11e6-80c6-d01d2d114b7f.png)
![screenshot from 2016-11-24 09-54-46](https://cloud.githubusercontent.com/assets/12674437/20592133/55145052-b22c-11e6-95a4-ef2115d17349.png)
![screenshot from 2016-11-24 09-54-57](https://cloud.githubusercontent.com/assets/12674437/20592134/551a11e0-b22c-11e6-9e17-215bc6a10862.png)
![screenshot from 2016-11-24 09-55-13](https://cloud.githubusercontent.com/assets/12674437/20592135/551f2716-b22c-11e6-9b84-6930fe0d9c24.png)
![screenshot from 2016-11-24 09-55-30](https://cloud.githubusercontent.com/assets/12674437/20592136/5523e1fc-b22c-11e6-9cd9-fc2ed97c6e74.png)
![screenshot from 2016-11-24 09-55-49](https://cloud.githubusercontent.com/assets/12674437/20592137/552ecd9c-b22c-11e6-9234-59236f2c9e1a.png)
![screenshot from 2016-11-24 09-56-03](https://cloud.githubusercontent.com/assets/12674437/20592138/553432f0-b22c-11e6-9b0a-931865cc3d5b.png)
![screenshot from 2016-11-24 09-56-17](https://cloud.githubusercontent.com/assets/12674437/20592139/553905a0-b22c-11e6-8233-2a58cfc07d0a.png)
![screenshot from 2016-11-24 09-56-32](https://cloud.githubusercontent.com/assets/12674437/20592140/553e8980-b22c-11e6-9d1e-ab96ec6d3d95.png)

### and yet
![screenshot from 2016-11-24 09-50-34](https://cloud.githubusercontent.com/assets/12674437/20591992/abeb2d02-b22b-11e6-8e4a-16292565aee3.png)

**Comment by ShalokShalom** [comment]
![screenshot_20161124_113815](https://cloud.githubusercontent.com/assets/6344099/20595541/950f8c4a-b23a-11e6-8cd0-5fdbf51ac264.png)

**Comment by Alien1993** [comment]
I'm having the same issue, I'm using Google DNS.
`host phoenix.vg` says this: 
`phoenix.vg has address 185.53.177.31`

Instead `host https://phoenix.vg` this:
`https://phoenix.vg has address 88.198.29.97`

On Chrome phoenix.vg return a similar page to the one posted by @ShalokShalom, instead https://phoenix.vg returns a 403 from nginx.

Hope this helps.

**Comment by szkrd** [comment]
Probably a github wiki or standalone md page would be more reliable, but of course it's up to you.
![20161211175645-w](https://cloud.githubusercontent.com/assets/1073260/21081674/a519c300-bfcb-11e6-8275-d0ba05303b32.jpg)

**Comment by athairus** [comment]
Spot the issue:
<img width="216" alt="screen shot 2016-12-16 at 1 38 59 pm" src="https://cloud.githubusercontent.com/assets/1216337/21279471/36be97be-c395-11e6-841a-021c3478f844.png">

The jerks who run ns2digitalocean.com aren't breaking any laws... but they broke my heart. It should be fixed now.

Wait at least 24 hours after this post and test away, let me know if there's any other issues.

**Comment by ShalokShalom** [comment]
The dot was missing?

**Comment by brandleesee** [comment]
@athairus All good from my end.
Trivial but the bookmark for 'Developers wanted' does not work.
One can always scroll down.

![screenshot from 2016-12-17 09-19-00](https://cloud.githubusercontent.com/assets/12674437/21285477/f8fe7fb6-c439-11e6-9565-a5c87a20b656.png)
